import torch
import torch.nn as nn
from torch.nn.functional import mse_loss
import torch.nn.functional as F

from shift_tta.registry import MODELS
from .supervised_contrastive_loss import SupConLoss
from torchvision.ops import roi_align


@MODELS.register_module()
class YOLOXConsistencyContrastiveLoss(nn.Module):
    """YOLOXContrastiveConsistencyLoss
    Args:
        weight_consistency_loss (float, optional): Weight of the consistency loss.
        weight_contrastive_loss (float, optional): Weight of the contrastive loss. 
        obj_weight (float, optional): Weight of the objectness consistency loss.
            Default to 1.0.
        reg_weight (float, optional): Weight of the regression consistency loss.
            Default to 1.0.
        cls_weight (float, optional): Weight of the classification consistency loss.
            Default to 1.0.
    """

    def __init__(self,
                 weight_consistency_loss=0.01,
                 weight_contrastive_loss=0.01,
                 obj_weight=1.0,
                 reg_weight=1.0,
                 cls_weight=1.0,
                 contrastive=False,
                 filter_pseudo_labels=None
        ):
        super(YOLOXConsistencyContrastiveLoss, self).__init__()
        self.weight_consistency_loss = weight_consistency_loss
        self.weight_contrastive_loss = weight_contrastive_loss
        self.obj_weight = obj_weight
        self.reg_weight = reg_weight
        self.cls_weight = cls_weight
        self.contrastive = contrastive
        self.filter_pseudo_labels = filter_pseudo_labels
        self.supconloss = SupConLoss(contrast_mode='one')
    
    def forward(self, inputs, targets, features_teacher, features_student, teacher_preds, student_preds, img_width, img_height, **kwargs):
        """Forward pass.
        Args:
            inputs: Dictionary of classification scores and bounding box
            refinements for the sampled proposals. For cls scores, the shape is
            (b*n) * (cats + 1), where n is sampled proposal in each image, cats
            is the total number of categories without the background. For bbox
            preds, the shape is (b*n) * (4*cats). This is the pseudo labels generated by the teacher.
            targets: Same output by bbox_head from the teacher output.
            feats: Tensor expected to have a shape of [batch_size, n_views, ...].
        Returns:
            The YOLOX consistency and contrastive loss.
        """
        ### --Consistency loss, loss=Consistency loss
        teacher_obj = targets["objectness"]
        teacher_reg = targets["bbox_pred"]
        teacher_cls = targets["cls_score"]

        student_obj = inputs["objectness"]
        student_reg = inputs["bbox_pred"]
        student_cls = inputs["cls_score"]

        obj_elements = 0
        reg_elements = 0
        cls_elements = 0
        obj_loss = 0.
        reg_loss = 0.
        cls_loss = 0.
        
        for (t_obj, t_reg, t_cls, s_obj, s_reg, s_cls) in zip(
            teacher_obj, teacher_reg, teacher_cls,
            student_obj, student_reg, student_cls,
        ):
            assert s_obj.shape == t_obj.shape
            assert s_reg.shape == t_reg.shape
            assert s_cls.shape == t_cls.shape

            _obj_loss = mse_loss(t_obj, s_obj, reduction="none")
            _cls_loss = mse_loss(t_cls, s_cls, reduction="none")
            _reg_loss = mse_loss(t_reg, s_reg, reduction="none")

            obj_loss += torch.sum(_obj_loss)
            reg_loss += torch.sum(_reg_loss)
            cls_loss += torch.sum(_cls_loss)

            obj_elements += _obj_loss.numel()
            reg_elements += _reg_loss.numel()
            cls_elements += _cls_loss.numel()

        obj_loss = obj_loss / obj_elements
        reg_loss = reg_loss / reg_elements
        cls_loss = cls_loss / cls_elements

        loss = self.obj_weight * obj_loss
        loss += self.reg_weight * reg_loss 
        loss += self.cls_weight * cls_loss 
        
        # Calculate weighted consistency loss
        consistency_loss = self.weight_consistency_loss * loss
        
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        contrastive_loss = torch.tensor(0.0).to(device)
        
        ### --Contrastive loss for multi scale features
        if self.contrastive:
            # Initialize loss to zero
            contrastive_loss_multi_scale = torch.tensor(0.0).to(device)
 
            for i in range(len(features_teacher)): ### len(features_teacher)
                ### --Keep only the first view
                '''teacher_obj[i] = teacher_obj[i][0, :, :, :].unsqueeze(0)
                teacher_reg[i] = teacher_reg[i][0, :, :, :].unsqueeze(0)
                teacher_cls[i] = teacher_cls[i][0, :, :, :].unsqueeze(0)

                student_obj[i] = student_obj[i][0, :, :, :].unsqueeze(0)
                student_reg[i] = student_reg[i][0, :, :, :].unsqueeze(0)
                student_cls[i] = student_cls[i][0, :, :, :].unsqueeze(0)'''
                
                features_student = list(features_student)
                features_student[i] = features_student[i][0, :, :, :].unsqueeze(0)
                
                features_teacher = list(features_teacher)
                features_teacher[i] = features_teacher[i][0, :, :, :].unsqueeze(0)
                ### --

                '''### H*W predictions
                H = features_teacher[i].shape[2]
                W = features_teacher[i].shape[3]
                teacher_pred1 = []
                for j in range(H):
                    for k in range (W):
                        teacher_pred1.append(teacher_cls[i][:, :, j, k])
                print("list of tensors:", teacher_pred1[0])'''
                        
                '''# Get the predictions
                teacher_pred = teacher_cls[i].reshape((6, -1)).T
                #print(teacher_pred[0, :])
        
                # Get probabilities
                teacher_prob = F.softmax(teacher_pred, dim=1)
        
                # Get max probabilities
                teacher_score, _ = torch.max(teacher_prob, dim=1)
        
                # Get class labels
                teacher_label = torch.argmax(teacher_prob, dim=1)
        
                # Create a 2D tensor with bboxes coordinates
                student_reg_boxes = student_reg[i].reshape((4, -1)).T
                teacher_reg_boxes = teacher_reg[i].reshape((4, -1)).T
                # print(student_reg_boxes[0,:]) ### First bbox, shape [num, 4] -> in each row a bbox'''
                
                # Get bboxes and labels
                teacher_reg_boxes = teacher_preds[0].bboxes
                student_reg_boxes = student_preds[0].bboxes
                teacher_label = teacher_preds[0].labels
                teacher_score = teacher_preds[0].scores
                
                # Filter pseudo labels based on threshold
                if self.filter_pseudo_labels is not None:
                    mask = teacher_score >= self.filter_pseudo_labels
                    student_reg_boxes = student_reg_boxes[mask]
                    teacher_score = teacher_score[mask]
                    teacher_label = teacher_label[mask]
                    teacher_reg_boxes = teacher_reg_boxes[mask]
                    #print(teacher_reg_boxes.shape)
                    #print(teacher_score)
                    #print(teacher_label)
                    #print(teacher_reg_boxes)
                    
                # If there are bboxes detected after filtering
                if len(teacher_reg_boxes):      
                    # Calculate object level features using ROIAlign
                    object_features_student = locate_feature_roialign(features_student[i], student_reg_boxes, img_width, img_height)
                    object_features_teacher = locate_feature_roialign(features_teacher[i], teacher_reg_boxes, img_width, img_height)

                    # Normalize object level features
                    object_features_student = nn.functional.normalize(object_features_student, dim=1)
                    object_features_teacher = nn.functional.normalize(object_features_teacher, dim=1)
        
                    # Compute contrastive loss
                    object_features_all = torch.stack([object_features_student, object_features_teacher], dim=1)
                    contrastive_loss = self.supconloss(object_features_all, teacher_label) # Use pseudo labels as ground truths for supervision
                    #print(f"Contrastive loss not weighted stage {i}: {contrastive_loss}")
          
                    # Add contrastive loss for each feature scale
                    contrastive_loss_multi_scale += contrastive_loss
            #print(len(teacher_reg_boxes))
            #print(teacher_reg_boxes)
            #print(student_reg_boxes)
            
            contrastive_loss = contrastive_loss_multi_scale * self.weight_contrastive_loss
            loss = consistency_loss + contrastive_loss
   
            '''print("Consistency loss!!!:", consistency_loss)                
            print("Contrastive loss!!!:", contrastive_loss)
            print("Final loss!!!:", loss)
            print()'''
        ### --
        
        return loss, consistency_loss, contrastive_loss
        
        
def locate_feature_roialign(feature_map, boxes, image_width, image_height):
    selected_features = []
    sx = feature_map.shape[3] / image_width
    sy = feature_map.shape[2] / image_height
    
    if len(boxes):
        # Add batch index as zeros, because batch_size = 1, all bboxes belong to the same image
        batch_idx = torch.zeros((boxes.shape[0], 1), device=feature_map.device) ### Only for batch_seze = 1
        # Concatenate batch index with box coordinates
        boxes_level = torch.cat([batch_idx, boxes], dim=1)
        
        boxes_level[:, 1] *= sx  # x1
        boxes_level[:, 2] *= sy  # y1
        boxes_level[:, 3] *= sx  # x2
        boxes_level[:, 4] *= sy  # y2
        
        selected_features_level = roi_align(feature_map, boxes_level, output_size=1, aligned=True)
        selected_features_level = torch.flatten(selected_features_level, start_dim=1)
        selected_features = selected_features_level
    else:
        selected_features = None
    return selected_features        
